### ISSUE TITLE
AI Documentation code and files were showing in pr but not in master code after merge 

### ISSUE THREAD

**Issue by HariharanUmapathi** [HariharanUmapathi/foss-event-aggregator#2]
@syedjaferk kindly look into it you have added a AI document generator for the python application In pull request i can see the github workflow configuration file but in master it's not showing

**Comment by syedjaferk** [comment]
@HariharanUmapathi I have actually removed it. It got included into the repo from my previous experimentation. So I removed it.

**Comment by HariharanUmapathi** [comment]
@syedjaferk thanks for the clarification
