### ISSUE TITLE
Events from ICFOSS Website

### ISSUE THREAD

**Issue by hammadbinsajjad** [HariharanUmapathi/foss-event-aggregator#4]
While exploring some websites to add, came across this website  [ICFOSS - Events](https://icfoss.in/events) which has quite a number of events. 

If these events suit the criteria for this project then I can try implementing a data extractor class to scrape the events by duplicating the requests which the website is using to fetch and display the data.

My approach for this implementation would be as follows.

1. Fetch the pages in a loop starting from page number 1
2. Extract the required events details from the response.
3. Check if next page exists and continue to fetch, break the loop otherwise.

**Comment by HariharanUmapathi** [comment]
Your approach is clear @hammadbinsajjad implement for ics foss and raise pr

**Comment by hammadbinsajjad** [comment]
Thank you, will start working on it today and make the PR once done with the implementation.
